import libreria

assert (libreria.valida_Dni("7288342") == False)
assert (libreria.valida_Dni("12345") == False)
assert (libreria.valida_Dni("123456789") == False)
assert (libreria.valida_Dni("123456") == False)
assert (libreria.valida_Dni("12345678") == True)
print("valida_Dni OK")

assert (libreria.valida_Vocal("a") == True)
assert (libreria.valida_Vocal("r") == False)
assert (libreria.valida_Vocal("i") == True)
assert (libreria.valida_Vocal("u") == True)
assert (libreria.valida_Vocal("f") == False)
print("valida_Vocal OK")

assert (libreria.valida_NroPar(5) == False)
assert (libreria.valida_NroPar(4) == True)
assert (libreria.valida_NroPar(21) == False)
assert (libreria.valida_NroPar(20) == True)
assert (libreria.valida_NroPar(1) == False)
print("valida_NroPar OK")

assert (libreria.es_Moneda_valido("EUROS") == True)
assert (libreria.es_Moneda_valido("INTI") == False)
assert (libreria.es_Moneda_valido("REAL") == False)
assert (libreria.es_Moneda_valido("YEN") == False)
assert (libreria.es_Moneda_valido("SOLES") == True)
print("es_Moneda_valido OK")

assert (libreria.es_EstadoCivil_valido("SOLTERO") == True)
assert (libreria.es_EstadoCivil_valido("ENAMORADO") == False)
assert (libreria.es_EstadoCivil_valido("COMPROMETIDO") == False)
assert (libreria.es_EstadoCivil_valido("CASADO") == True)
assert (libreria.es_EstadoCivil_valido("VIUDO") == True)
print("es_EstadoCivil_valido OK")

assert (libreria.validamayorEdad(18) == True)
assert (libreria.validamayorEdad(30) == True)
assert (libreria.validamayorEdad(12) == False)
assert (libreria.validamayorEdad(76) == True)
assert (libreria.validamayorEdad(1) == False)
print("validamayorEdad OK")

assert (libreria.validaNroTelefono("984645040") == True)
assert (libreria.validaNroTelefono("984123") == False)
assert (libreria.validaNroTelefono("963875424") == True)
assert (libreria.validaNroTelefono("98464504032") == False)
assert (libreria.validaNroTelefono("984876635423") == False)
print("validaNroTelefono OK")

assert (libreria.validarAñoNacimiento(1958) == True)
assert (libreria.validarAñoNacimiento(1950) == True)
assert (libreria.validarAñoNacimiento(1935) == False)
assert (libreria.validarAñoNacimiento(1905) == False)
assert (libreria.validarAñoNacimiento(1998) == True)
print("validarAñoNacimiento OK")

assert (libreria.ValidarNumeroImpar(123)==True)
assert (libreria.ValidarNumeroImpar(1234)==False)
assert (libreria.ValidarNumeroImpar(12)==False)
assert (libreria.ValidarNumeroImpar(23)==True)
assert (libreria.ValidarNumeroImpar(330)==False)
print("ValidarNumeroImpar OK")

assert (libreria.validarNroCuenta("123456789067895432")==True)
assert (libreria.validarNroCuenta("1234567890")==False)
assert (libreria.validarNroCuenta("235762387642923492")==True)
assert (libreria.validarNroCuenta("1234567890678")==False)
assert (libreria.validarNroCuenta("762935196732873478")==True)
print("validarNroCuenta OK")

assert (libreria.validarRUC("01234529857")== True)
assert (libreria.validarRUC("01234529857062")== False)
assert (libreria.validarRUC("012345")== False)
assert (libreria.validarRUC("01987862534")== True)
assert (libreria.validarRUC("01234628749")== True)
print("validarRUC OK")

assert (libreria.validarID("1234567")==True)
assert (libreria.validarID("9876543")==True)
assert (libreria.validarID("1234")==False)
assert (libreria.validarID("12345670")==False)
assert (libreria.validarID("1123232")==True)
print("validarID OK")

assert (libreria.validarMenorEdad(20)==False)
assert (libreria.validarMenorEdad(2)==True)
assert (libreria.validarMenorEdad(22)==False)
assert (libreria.validarMenorEdad(12)==True)
assert (libreria.validarMenorEdad(32)==False)
print("validarMenorEdad OK")

assert (libreria.validarMes("NOVIEMBRE")==True)
assert (libreria.validarMes("MARTES")==False)
assert (libreria.validarMes("DICIEMBRE")==True)
assert (libreria.validarMes("ENERO")==True)
assert (libreria.validarMes("JUEVES")==False)
print("validaMes OK")

assert (libreria.valida_Letra("A")==True)
assert (libreria.valida_Letra("B")==False)
assert (libreria.valida_Letra("G")==True)
assert (libreria.valida_Letra("W")==False)
assert (libreria.valida_Letra("X")==False)
print("valida_Letra OK")
